query getAthletes {
    users(
        hasRole: {
            column: NAME,
            value: "athlete"
        }
) {
        id
        firstname
        lastname
        nickname
        imageUrl
        groups {
            id
        }
    }
}