query getCoaches {
    users(
        hasRole: {
            column: NAME,
            value: "coach"
        }
) {
        id
        firstname
        lastname
        nickname
        imageUrl
    }
}