mutation forgotPassword ($email: String!, $url: String!) {
    forgotPassword(input: {
        email: $email
        reset_password_url: {
            url: $url
        }
    }) {
        status
        message
    }
}
