query getGroupPagination ($first: Int!, $page: Int!, $orderBy: [QueryGroupsPaginateOrderByRelationOrderByClause!], $name: String) {
    groupsPaginate(first: $first, page: $page, orderBy: $orderBy, name: $name) {
        paginatorInfo {
            total
            currentPage
            hasMorePages
            lastItem
            lastPage
            perPage
            count
        }
        data {
            id
            name
            athletes {
                id
                firstname
                lastname
                nickname
                imageUrl
            }
            coaches {
                id
                firstname
                lastname
                nickname
                imageUrl
            }
        }
    }
}