#import "./fragments/user.fragment.gql"
#import "./fragments/training.fragment.gql"

query me {
    me {
        ...UserFragment
        upcomingTrainingsAsAthlete {
            ...TrainingFragment
        }
        upcomingTrainingsAsCoach {
            ...TrainingFragment
        }
        roles {
            name
            permissions {
                name
            }
        }

    }
}