query me {
    me {
        id
        firstname
        lastname
        nickname
        birthdate
        phone
        email
        image
        imageUrl
        roles {
            name
            permissions {
                name
            }
        }

    }
}