#import "./fragments/user.fragment.gql"

query profileData {
    me {
        ...UserFragment
        notificationSettingsPush {
            id
            name
        }
        notificationSettingsEmail {
            id
            name
        }
        roles {
            name
            permissions {
                name
            }
        }

    }
}