mutation register (
    $firstname: String!,
    $lastname: String!,
    $nickname: String,
    $phone: String,
    $birthdate: Date!,
    $email: String!,
    $password: String!,
    $password_confirmation: String!,
    $url: String!
) {
    register(input: {
        firstname: $firstname,
        lastname: $lastname,
        nickname: $nickname,
        birthdate: $birthdate,
        phone: $phone,
        email: $email,
        password: $password,
        password_confirmation:
        $password_confirmation
        verification_url: {
            url: $url
        }
    }) {
        status
    }
}