mutation resetPassword ($email: String!, $token: String!, $password: String!, $password_confirmation: String!) {
    resetPassword(input: {
        email: $email,
        token: $token
        password: $password
        password_confirmation: $password_confirmation
    }) {
        status
        message
    }
}