mutation updateTraining (
    $id: ID!,
    $name: String,
    $description: String,
    $status: Boolean,
    $date_start: DateTime,
    $date_end: DateTime,
    $location: ID,
    $athletes: [ID!]
    $coaches: [ID!]
    $groups: [ID!]
) {
    updateTraining(id: $id, input: {
        name: $name,
        description: $description,
        status: $status,
        date_start: $date_start,
        date_end: $date_end,
        location: $location,
        athletes: $athletes,
        coaches: $coaches,
        groups: $groups
    }) {
        id
        name
        description
        status
        date_start
        date_end
        location {
            id
            name
        }
        groups {
            id
            name
        }
        coaches {
            id
            firstname
            lastname
            nickname
            imageUrl
        }
        athletes {
            id
            firstname
            lastname
            nickname
            imageUrl
        }
    }
}