query getUsersPagination ($first: Int!, $page: Int!, $orderBy: [QueryUsersOrderByOrderByClause!], $filter: String) {
    users(first: $first, page: $page, orderBy: $orderBy, firstname: $filter) {
        paginatorInfo {
            total
            currentPage
            hasMorePages
            lastItem
            lastPage
            perPage
            count
        }
        data {
            id
            firstname
            lastname
            birthdate
            nickname
            phone
            email
            approved
        }
    }
}