mutation updateUser (
    $id: ID!,
    $firstname: String,
    $lastname: String,
    $nickname: String,
    $phone: String,
    $birthdate: Date,
    $email: String,
    $roles: [ID!]
) {
    updateUser(id: $id, input: {
        firstname: $firstname,
        lastname: $lastname,
        nickname: $nickname,
        birthdate: $birthdate,
        phone: $phone,
        email: $email,
        roles: $roles,
    }) {
        id
        firstname
        lastname
        nickname
        birthdate
        phone
        email
        roles {
            id
            name
        }
    }
}