#import "./fragments/user.fragment.gql"

mutation updateUser (
    $id: ID!,
    $firstname: String,
    $lastname: String,
    $nickname: String,
    $phone: String,
    $birthdate: Date,
    $email: String,
    $roles: UpdateUserRoleInput,
    $groups: UpdateUserGroupInput,
) {
    updateUser(id: $id, input: {
        firstname: $firstname,
        lastname: $lastname,
        nickname: $nickname,
        birthdate: $birthdate,
        phone: $phone,
        email: $email,
        roles: $roles,
        groups: $groups,
    }) {
        ...UserFragment
    }
}