query getUsersPagination ($first: Int!, $page: Int!, $orderBy: [QueryUsersPaginationOrderByOrderByClause!], $firstname: String, $lastname: String, $nickname: String, $hasRole: QueryUsersPaginationHasRoleWhereHasConditions, $where: QueryUsersPaginationWhereWhereConditions, $approved: Boolean) {
    usersPagination(first: $first, page: $page, orderBy: $orderBy, firstname: $firstname, lastname: $lastname, nickname: $nickname, hasRole: $hasRole, where: $where, approved: $approved) {
        paginatorInfo {
            total
            currentPage
            hasMorePages
            lastItem
            lastPage
            perPage
            count
        }
        data {
            id
            firstname
            lastname
            birthdate
            created_at
            nickname
            phone
            email
            imageUrl
            roles {
                id
                name
            }
            groups {
                id
                name
            }
            approved
        }
    }
}